phonegap plugin add https://github.com/mkuklis/phonegap-websocket
phonegap plugin add cordova-plugin-inappbrowser
phonegap plugin add cordova-plugin-device
phonegap plugin add cordova-plugin-media
phonegap plugin add phonegap-plugin-push
phonegap plugin add cordova-plugin-splashscreen
phonegap plugin add cordova-plugin-whitelist
phonegap plugin add cordova-plugin-file
phonegap plugin add cc.fovea.cordova.purchase
phonegap plugin add cordova-plugin-google-analytics
phonegap plugin add ionic-plugin-keyboard
